# NEXUS PROTOCOL - Docker Compose Production Deployment
# Complete production stack with Nginx, SSL, and monitoring

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nexus-postgres
    restart: always
    environment:
      POSTGRES_DB: nexusprotocol
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - nexus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend SSH Proxy + API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexus-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3002
      SSH_PROXY_PORT: 3002
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/nexusprotocol
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      CORS_ORIGIN: https://${DOMAIN}
      FRONTEND_URL: https://${DOMAIN}
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nexus-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (Nginx serves built React app)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexus-frontend
    restart: always
    environment:
      VITE_API_URL: https://${DOMAIN}/api
      VITE_WS_URL: wss://${DOMAIN}
      VITE_SSH_PROXY_URL: https://${DOMAIN}
    networks:
      - nexus-network

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: nexus-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/nexus-protocol.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/nexus-protocol/frontend
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - nexus-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: nexus-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # Redis (optional - for caching)
  redis:
    image: redis:7-alpine
    container_name: nexus-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - nexus-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  nexus-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
